// <auto-generated />
using System;
using AOIntuneAlerts.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AOIntuneAlerts.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260202100046_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AOIntuneAlerts.Domain.Aggregates.Alert.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("WasSent")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeviceId");

                    b.HasIndex("SentAt");

                    b.ToTable("Alerts", (string)null);
                });

            modelBuilder.Entity("AOIntuneAlerts.Domain.Aggregates.Alert.AlertCooldown", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CooldownExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastAlertSent")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "AlertType")
                        .IsUnique();

                    b.ToTable("AlertCooldowns", (string)null);
                });

            modelBuilder.Entity("AOIntuneAlerts.Domain.Aggregates.Alert.AlertRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("MinimumSeverity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.ToTable("AlertRecipients", (string)null);
                });

            modelBuilder.Entity("AOIntuneAlerts.Domain.Aggregates.Alert.PortalUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AzureAdObjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserPrincipalName")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.HasKey("Id");

                    b.HasIndex("AzureAdObjectId")
                        .IsUnique();

                    b.ToTable("PortalUsers", (string)null);
                });

            modelBuilder.Entity("AOIntuneAlerts.Domain.Aggregates.ComplianceRule.ComplianceRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ApplicableOs")
                        .HasColumnType("int");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RuleType")
                        .HasColumnType("int");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("RuleType");

                    b.ToTable("ComplianceRules", (string)null);
                });

            modelBuilder.Entity("AOIntuneAlerts.Domain.Aggregates.ComplianceRule.VendorSupportDate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndOfSupportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OperatingSystemType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VersionPattern")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OperatingSystemType", "VersionPattern");

                    b.ToTable("VendorSupportDates", (string)null);
                });

            modelBuilder.Entity("AOIntuneAlerts.Domain.Aggregates.Device.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ComplianceState")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DeviceType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndOfSupportDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IntuneComplianceState")
                        .HasColumnType("int");

                    b.Property<string>("IntuneDeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsManaged")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastComplianceEvaluationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSyncDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserPrincipalName")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.HasKey("Id");

                    b.HasIndex("IntuneDeviceId")
                        .IsUnique();

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("AOIntuneAlerts.Domain.Aggregates.Device.DeviceBrowser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCompliant")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastCheckedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceBrowsers", (string)null);
                });

            modelBuilder.Entity("AOIntuneAlerts.Domain.Aggregates.Device.DeviceComplianceIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceComplianceIssues", (string)null);
                });

            modelBuilder.Entity("AlertAlertRecipient", b =>
                {
                    b.Property<Guid>("AlertId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlertRecipientId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AlertId", "AlertRecipientId");

                    b.HasIndex("AlertRecipientId");

                    b.ToTable("AlertAlertRecipient");
                });

            modelBuilder.Entity("AOIntuneAlerts.Domain.Aggregates.Alert.AlertRecipient", b =>
                {
                    b.OwnsOne("AOIntuneAlerts.Domain.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<Guid>("AlertRecipientId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("nvarchar(320)")
                                .HasColumnName("Email");

                            b1.HasKey("AlertRecipientId");

                            b1.ToTable("AlertRecipients");

                            b1.WithOwner()
                                .HasForeignKey("AlertRecipientId");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("AOIntuneAlerts.Domain.Aggregates.Alert.PortalUser", b =>
                {
                    b.OwnsOne("AOIntuneAlerts.Domain.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<Guid>("PortalUserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("nvarchar(320)")
                                .HasColumnName("Email");

                            b1.HasKey("PortalUserId");

                            b1.ToTable("PortalUsers");

                            b1.WithOwner()
                                .HasForeignKey("PortalUserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("AOIntuneAlerts.Domain.Aggregates.ComplianceRule.VendorSupportDate", b =>
                {
                    b.OwnsOne("AOIntuneAlerts.Domain.ValueObjects.SemVer", "MinimumVersion", b1 =>
                        {
                            b1.Property<Guid>("VendorSupportDateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Build")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("MinVersionBuild");

                            b1.Property<int>("Major")
                                .HasColumnType("int")
                                .HasColumnName("MinVersionMajor");

                            b1.Property<int>("Minor")
                                .HasColumnType("int")
                                .HasColumnName("MinVersionMinor");

                            b1.Property<int>("Patch")
                                .HasColumnType("int")
                                .HasColumnName("MinVersionPatch");

                            b1.Property<string>("PreRelease")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("MinVersionPreRelease");

                            b1.HasKey("VendorSupportDateId");

                            b1.ToTable("VendorSupportDates");

                            b1.WithOwner()
                                .HasForeignKey("VendorSupportDateId");
                        });

                    b.Navigation("MinimumVersion")
                        .IsRequired();
                });

            modelBuilder.Entity("AOIntuneAlerts.Domain.Aggregates.Device.Device", b =>
                {
                    b.OwnsOne("AOIntuneAlerts.Domain.ValueObjects.OperatingSystemInfo", "OperatingSystem", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BuildNumber")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("OsBuildNumber");

                            b1.Property<string>("Edition")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("OsEdition");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("OsName");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("OsType");

                            b1.HasKey("DeviceId");

                            b1.ToTable("Devices");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");

                            b1.OwnsOne("AOIntuneAlerts.Domain.ValueObjects.SemVer", "Version", b2 =>
                                {
                                    b2.Property<Guid>("OperatingSystemInfoDeviceId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Build")
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("OsVersionBuild");

                                    b2.Property<int>("Major")
                                        .HasColumnType("int")
                                        .HasColumnName("OsVersionMajor");

                                    b2.Property<int>("Minor")
                                        .HasColumnType("int")
                                        .HasColumnName("OsVersionMinor");

                                    b2.Property<int>("Patch")
                                        .HasColumnType("int")
                                        .HasColumnName("OsVersionPatch");

                                    b2.Property<string>("PreRelease")
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("OsVersionPreRelease");

                                    b2.HasKey("OperatingSystemInfoDeviceId");

                                    b2.ToTable("Devices");

                                    b2.WithOwner()
                                        .HasForeignKey("OperatingSystemInfoDeviceId");
                                });

                            b1.Navigation("Version")
                                .IsRequired();
                        });

                    b.Navigation("OperatingSystem")
                        .IsRequired();
                });

            modelBuilder.Entity("AOIntuneAlerts.Domain.Aggregates.Device.DeviceBrowser", b =>
                {
                    b.HasOne("AOIntuneAlerts.Domain.Aggregates.Device.Device", null)
                        .WithMany("Browsers")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AOIntuneAlerts.Domain.ValueObjects.BrowserInfo", "BrowserInfo", b1 =>
                        {
                            b1.Property<Guid>("DeviceBrowserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("BrowserName");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("BrowserType");

                            b1.HasKey("DeviceBrowserId");

                            b1.ToTable("DeviceBrowsers");

                            b1.WithOwner()
                                .HasForeignKey("DeviceBrowserId");

                            b1.OwnsOne("AOIntuneAlerts.Domain.ValueObjects.SemVer", "Version", b2 =>
                                {
                                    b2.Property<Guid>("BrowserInfoDeviceBrowserId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Build")
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("BrowserVersionBuild");

                                    b2.Property<int>("Major")
                                        .HasColumnType("int")
                                        .HasColumnName("BrowserVersionMajor");

                                    b2.Property<int>("Minor")
                                        .HasColumnType("int")
                                        .HasColumnName("BrowserVersionMinor");

                                    b2.Property<int>("Patch")
                                        .HasColumnType("int")
                                        .HasColumnName("BrowserVersionPatch");

                                    b2.Property<string>("PreRelease")
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("BrowserVersionPreRelease");

                                    b2.HasKey("BrowserInfoDeviceBrowserId");

                                    b2.ToTable("DeviceBrowsers");

                                    b2.WithOwner()
                                        .HasForeignKey("BrowserInfoDeviceBrowserId");
                                });

                            b1.Navigation("Version")
                                .IsRequired();
                        });

                    b.Navigation("BrowserInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("AOIntuneAlerts.Domain.Aggregates.Device.DeviceComplianceIssue", b =>
                {
                    b.HasOne("AOIntuneAlerts.Domain.Aggregates.Device.Device", null)
                        .WithMany("ComplianceIssues")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlertAlertRecipient", b =>
                {
                    b.HasOne("AOIntuneAlerts.Domain.Aggregates.Alert.Alert", null)
                        .WithMany()
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AOIntuneAlerts.Domain.Aggregates.Alert.AlertRecipient", null)
                        .WithMany()
                        .HasForeignKey("AlertRecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AOIntuneAlerts.Domain.Aggregates.Device.Device", b =>
                {
                    b.Navigation("Browsers");

                    b.Navigation("ComplianceIssues");
                });
#pragma warning restore 612, 618
        }
    }
}
